
[functions.trigger-netlify-build]
enabled = true
verify_jwt = true
import_map = "./functions/trigger-netlify-build/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/trigger-netlify-build/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/trigger-netlify-build/*.html" ]
